language: node_js
node_js:
    - "6"
    - "7"
    - "8"
script: npm test
notifications:
    email:
        recipients:
            - zlatkofedor@cherryprojects.com
        on_success: change
        on_failure: always
